### ISSUE TITLE
osx build

### ISSUE THREAD

**Issue by mariusnita** [robertswiecki/intrace#9]
Hi. This seems like a really cool tool. Can it be built on osx?

```
make
CC debug.c
In file included from debug.c:35:
In file included from ./intrace.h:84:
./ipv4.h:29:17: error: field has incomplete type 'struct icmphdr'
        struct icmphdr icmph;
                       ^
./ipv4.h:29:9: note: forward declaration of 'struct icmphdr'
        struct icmphdr icmph;
               ^
1 error generated.
make: *** [debug.o] Error 1
```

**Comment by ishan28mkip** [comment]
+1 I receive the same error, would be great if it would build on osx.

**Comment by robertswiecki** [comment]
I don't think it's OSX buildable as it uses RAW TCP sockets. I think under OS-X it'd require some form of AF_PACKET, though I don't have access to OS-X to try that.

I think it's Linux only for now.
